version: "3"

services:
  redis:
    image: redis

  django-app:
    depends_on:
      - redis
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/djangoApp/

    command: python manage.py runserver 0.0.0.0:8000
